server:
  port: 8081

Spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: study
    password: study


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #服务器连接密码，默认为空
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中最小空闲连接
        min-idle: 0
        #连接池中最大空闲连接
        max-idle: 8
    #连接超时时间（毫秒）
    timeout: 30000
